# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 240)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.NameText = QtWidgets.QLineEdit(Form)
        self.NameText.setGeometry(QtCore.QRect(170, 15, 221, 20))
        self.NameText.setObjectName("NameText")
        self.StepenText = QtWidgets.QLineEdit(Form)
        self.StepenText.setGeometry(QtCore.QRect(170, 45, 221, 20))
        self.StepenText.setObjectName("StepenText")
        self.MolotText = QtWidgets.QLineEdit(Form)
        self.MolotText.setGeometry(QtCore.QRect(170, 75, 221, 20))
        self.MolotText.setObjectName("MolotText")
        self.VkysText = QtWidgets.QLineEdit(Form)
        self.VkysText.setGeometry(QtCore.QRect(170, 105, 221, 20))
        self.VkysText.setObjectName("VkysText")
        self.SumText = QtWidgets.QLineEdit(Form)
        self.SumText.setGeometry(QtCore.QRect(170, 135, 221, 20))
        self.SumText.setObjectName("SumText")
        self.ObemText = QtWidgets.QLineEdit(Form)
        self.ObemText.setGeometry(QtCore.QRect(170, 165, 221, 20))
        self.ObemText.setObjectName("ObemText")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 200, 101, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Название сорта:"))
        self.label_2.setText(_translate("Form", "Степень обжарки:"))
        self.label_3.setText(_translate("Form", "Молотый/в зернах:"))
        self.label_4.setText(_translate("Form", "Описание вкуса:"))
        self.label_5.setText(_translate("Form", "Цена:"))
        self.label_6.setText(_translate("Form", "Объем упаковки:"))
        self.pushButton.setText(_translate("Form", "Сохранить"))
