# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(791, 524)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 791, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.NewButton = QtWidgets.QPushButton(Form)
        self.NewButton.setGeometry(QtCore.QRect(34, 480, 101, 31))
        self.NewButton.setObjectName("NewButton")
        self.EditButton = QtWidgets.QPushButton(Form)
        self.EditButton.setGeometry(QtCore.QRect(140, 480, 101, 31))
        self.EditButton.setObjectName("EditButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.NewButton.setText(_translate("Form", "Добавить"))
        self.EditButton.setText(_translate("Form", "Редактировать"))
